### PR TITLE
Fix selection

### PR DESCRIPTION
**Pull request by ttt-77**
1.	Modify the Tasti Engine so that the score for each blob represents the estimated number of output rows.
2.	Fix the approximate selection algorithm.

### CODE REVIEW

**Comment by ttt-77** [comment]
@ddkang Could you please review this PR?

**Comment by ddkang** [comment]
I'd like to keep the score function and just modify it if possible, to allow for different implementations

**Comment by ttt-77** [comment]
https://github.com/ddkang/aidb/blob/a69a2027a823646e9a58b68199ddb0ec6fcae84b/aidb/engine/tasti_engine.py#L96-L131
We have a score function within the Tasti Engine that can be modified for different implementations. Should we move it to each query engine?

**Comment by ddkang** [comment]
Are there situations where the query implementation wants to use a different propagation method? If not maybe that's okay then.

**Comment by ttt-77** [comment]
We don't have that situation currently, but we can modify it later if needed.

**Review by ddkang — APPROVED** [review]

**Pull request merged**
