### PR TITLE
Support for python 3.12

### PR DESCRIPTION
**Pull request by hjk1030**
Most packages mentioned in issue #128 have python 3.12 compatible versions now, so it is possible to install the updated requirements now.

### CODE REVIEW

**Comment by continue-revolution** [comment]
can you verify if PyTorch 3.12 with CUDA (and potentially with xformers) is compatible with Python 3.12? If not, I would prefer to stay at Python 3.11

**Comment by hjk1030** [comment]
Pytorch 2.2.2 and xformers 0.0.25.post1 can be installed under python 3.12 using pip, though it needs a lot of memory to build wheel for xformers as python 3.12 version of pre-built wheel is not provided

**Comment by continue-revolution** [comment]
Then I would propose to stay with python 3.11 for now because pytorch and xformers are widely used in almost all locally hosted GenAI applications.

**Comment by ddkang** [comment]
Can we test 3.8, 3.11, and 3.12?

**Comment by hjk1030** [comment]
I've modified the workflow to run the tests under three different Python versions. Also I modified requirements.txt a bit to be compatible with Python 3.8.

**Review by ddkang — APPROVED** [review]

**Pull request merged**
