### PR TITLE
Nested queries and where-in clauses

### PR DESCRIPTION
**Pull request by shg8**
Add support for nested queries and where-in clauses, addressing #45.

* Refactor `Query` class to recursively find tables, columns, and filtering predicates in sub-queries
* A predicate containing sub-queries is satisfied if and only if all tables referenced in the sub-query are satisfied
* Ensure compatibility with * at any level
* Add support for where-in clause for both sub-queries and literals
* Add new tests to Actions workflow

### Testing Samples
```
SELECT * FROM colors02 WHERE object_id > (SELECT AVG(object_id) FROM objects00 WHERE y_max < (SELECT AVG(object_id) FROM colors02));
SELECT * FROM colors02 WHERE object_id IN (SELECT object_id FROM colors02 WHERE color = 'grayish_blue');
```

### CODE REVIEW

**Comment by ttt-77** [comment]
The Github check doesn't work. Could you solve it? @shg8

**Comment by ttt-77** [comment]
Could you submit a branch in this repo so that I can run it in local conveniently?

**Comment by shg8** [comment]
Hi Tengjun, I believe you need to manually approve the tests as detailed [here](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks). [All tests passed](https://github.com/shg8/aidb/actions/runs/6987032210) on my fork if you want to check it out.

**Comment by ttt-77** [comment]
This is one way to support nested query, but there are too many judgments. I think the class FilteringClause is not necessary, the better way is directly using the parsing results from sqlglot. You can refer to what I did in this branch. https://github.com/ddkang/aidb/blob/c33ef0ee27062958640147ca80e68522169c3ad8/aidb/query/query.py

**Comment by ttt-77** [comment]
For the format, 1. keep two blank lines between function. 2. Single quotation

**Comment by ddkang** [comment]
Hi @shg8 , thanks for putting this PR together! We are working on an automatic formatting script to help with the formatting issues, sorry about that.

We've also just made the sqlglot fork public here: https://github.com/ddkang/sqlglot

As @ttt-77 mentioned, I think it's better to push this logic into sqlglot itself. Please let me know if anything is unclear and thank you for your help! You can email me directly to be added to our development slack.

**Comment by shg8** [comment]
Hi @ttt-77 and @ddkang, thanks for your feedback. I avoided refactoring too much of the existing logic (FilteringClause, FilteringPredicate). Since we convert filtering clauses to CNF first, I don't think we could get around FilteringClause. Is there a specific vision that you have for how this should be implemented?

**Comment by ttt-77** [comment]
What does table dependencies mean? 
You need to use CNF conversion first. But for each filter predicate, you can directly use sqlglot parsing result rather than converting it into FilteringClause.
This is an example of the output of filtering predicates. Is there any issue to extract table for expression in this format?
Screenshot 2023-11-26 at 12 12 24

**Pull request closed without merging**
